# WashWise 配置文件

# 日志配置
log:
  level: "trace"  # 日志等级: debug, info, warn, error, fatal, panic
  dir: "logs"    # 日志目录

# 数据库配置
database:
  path: "./data/washwise.db"

# 商店ID列表
shops:
  - "202401041041470000069996565184"
  - "202401041044000000069996552384"
  - "202302071714530000012067133598"

# 服务器配置
server:
  host: "0.0.0.0"
  port: 8000

# 定时任务周期配置（单位：秒）
cron:
  enabled: false
  # 获取机器类型的周期（大周期）
  machine_types_interval: 3600 # 1小时

  # 获取机器列表的周期（中等周期）
  machines_interval: 300 # 5分钟

  # 获取机器详情的周期（短周期）
  machine_details_interval: 30 # 30秒
